name: ysr_magicanimate_real
channels:
  - pytorch
  - nvidia
dependencies:
  - python=3.10
  - pytorch=2.0.0
  # - torchvision=0.15.1
  # - torchaudio=2.0.2
  - pytorch-cuda=11.7
  - pip
  - pip:
      - absl-py==2.0.0
      - accelerate==0.24.1
      - addict==2.4.0
      - aiofiles==23.2.1
      - aliyun-python-sdk-core==2.14.0
      - aliyun-python-sdk-kms==2.16.2
      - altair==5.2.0
      - annotated-types==0.6.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.2.0
      - asttokens==2.4.1
      - attrs==23.2.0
      - av==11.0.0
      - bcrypt==4.1.2
      - black==23.12.1
      - boto3==1.34.15
      - botocore==1.34.15
      - braceexpand==0.1.7
      - cachetools==5.3.2
      - certifi==2023.11.17
      - cffi==1.16.0
      - charset-normalizer==3.3.2
      - chumpy==0.70
      - click==8.1.7
      - cloudpickle==3.0.0
      - cmake==3.28.1
      - comm==0.2.1
      - contourpy==1.2.0
      - controlnet-aux==0.0.7
      - crcmod==1.7
      - cryptography==41.0.7
      - cycler==0.12.1
      - cython==3.0.7
      - decorator==5.1.1
      - decord==0.6.0
      - opencv-python
      - gradio
      - git+https://github.com/facebookresearch/detectron2@main#subdirectory=projects/DensePose
      - diffusers==0.27.2
      - einops==0.7.0
      - exceptiongroup==1.2.0
      - executing==2.0.1
      - fastapi==0.109.0
      - ffmpy==0.3.1
      - flatbuffers==23.5.26
      - fonttools==4.47.0
      - fsspec==2023.12.2
      - fvcore==0.1.5.post20221221
      - google-auth==2.26.2
      - google-auth-oauthlib==1.2.0
      - gradio==4.14.0
      - gradio-client==0.8.0
      - grpcio==1.60.0
      - h11==0.14.0
      - hf-transfer==0.1.4
      - hjson==3.1.0
      - httpcore==1.0.2
      - httpx==0.26.0
      - huggingface-hub==0.20.2
      - hydra-core==1.3.2
      - idna==3.6
      - imageio==2.33.1
      - importlib-metadata==7.0.1
      - importlib-resources==6.1.1
      - iopath==0.1.9
      - ipython==8.20.0
      - ipywidgets==8.1.1
      - jedi==0.19.1
      - jmespath==0.10.0
      - json-tricks==3.17.3
      - jsonschema==4.20.0
      - jsonschema-specifications==2023.12.1
      - jupyterlab-widgets==3.0.9
      - kiwisolver==1.4.5
      - lazy-loader==0.3
      - lit==17.0.6
      - markdown==3.5.1
      - markdown-it-py==3.0.0
      - matplotlib==3.8.2
      - matplotlib-inline==0.1.6
      - mdurl==0.1.2
      - mediapipe==0.10.9
      - megfile==2.2.10.post1
      - mmengine==0.10.2
      - model-index==0.1.11
      - msgpack==1.0.7
      - munkres==1.1.4
      - mypy-extensions==1.0.0
      - ninja==1.11.1.1
      - numpy==1.26.3
      - oauthlib==3.2.2
      - omegaconf==2.3.0
      - opencv-contrib-python==4.9.0.80
      - opencv-python==4.9.0.80
      - opencv-python-headless==4.9.0.80
      - opendatalab==0.0.10
      - openmim==0.3.9
      - openxlab==0.0.33
      - ordered-set==4.1.0
      - orjson==3.9.10
      - oss2==2.17.0
      - packaging==23.2
      - pandas==2.1.4
      - paramiko==3.4.0
      - parso==0.8.3
      - pathspec==0.12.1
      - pexpect==4.9.0
      - pillow==9.5.0
      - platformdirs==4.1.0
      - portalocker==2.8.2
      - prompt-toolkit==3.0.43
      - protobuf==3.20.3
      - psutil==5.9.7
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - py-cpuinfo==9.0.0
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pycocotools==2.0.7
      - pycparser==2.21
      - pycryptodome==3.19.1
      - pydantic==2.5.3
      - pydantic-core==2.14.6
      - pydub==0.25.1
      - pyfacer==0.0.4
      - pygments==2.17.2
      - pynacl==1.5.0
      - pyparsing==3.1.1
      - pyre-extensions==0.0.29
      - python-multipart==0.0.6
      - pytz==2023.3.post1
      - pyyaml==6.0.1
      - referencing==0.32.1
      - regex==2023.12.25
      - requests==2.28.2
      - requests-oauthlib==1.3.1
      - rich==13.4.2
      - rpds-py==0.17.1
      - rsa==4.9
      - s3transfer==0.10.0
      - safetensors==0.4.1
      - scikit-image==0.22.0
      - scipy==1.11.4
      - semantic-version==2.10.0
      - setuptools==60.2.0
      - shapely==2.0.2
      - shellingham==1.5.4
      - six==1.16.0
      - sniffio==1.3.0
      - sounddevice==0.4.6
      - stack-data==0.6.3
      - starlette==0.35.1
      - tabulate==0.9.0
      - tensorboard==2.15.1
      - tensorboard-data-server==0.7.2
      - termcolor==2.4.0
      - terminaltables==3.1.10
      - tifffile==2023.12.9
      - timm==0.9.12
      - tokenizers==0.13.3
      - tomli==2.0.1
      - tomlkit==0.12.0
      - toolz==0.12.0
      - tqdm==4.65.2
      - traitlets==5.14.1
      - transformers==4.31.0
      - typer==0.9.0
      - typing-extensions==4.9.0
      - typing-inspect==0.9.0
      - tzdata==2023.4
      - urllib3==1.26.18
      - uvicorn==0.25.0
      - validators==0.22.0
      - wcwidth==0.2.13
      - webdataset==0.2.86
      - websockets==11.0.3
      - werkzeug==3.0.1
      - widgetsnbextension==4.0.9
      - xformers==0.0.19
      - xtcocotools==1.14.3
      - yacs==0.1.8
      - yapf==0.40.2
      - zipp==3.17.0