image_finetune: false
output_dir: "/data/code/yangshurong/magictrain"
pretrained_model_path: "/data/code/yangshurong/cache/StableDiffusion"
pretrained_vae_path: "/data/code/yangshurong/cache/magic_pretrain/sd-vae-ft-mse"

# ip_ckpt: "/data/work/IP-Adapter/IP-Adapter/models/ip-adapter-full-face_sd15.bin"
pretrained_appearance_encoder_path: "/data/code/yangshurong/cache/magic_pretrain/MagicAnimate/appearance_encoder"
pretrained_controlnet_path: ""

# motion_module: "/data/code/yangshurong/cache/magic_pretrain/AnimateDiff/v3_sd15_mm.ckpt"
motion_module: ""
inference_config: "configs/inference/magic_inference.yaml"
pretrained_unet_path: ""

model_type: "unet_magic_noiseAttenST"
train_loss: "mse"
train_cross_rate_step:
  0: 0.2
train_warp_rate_step:
  0: 0.5
  15000: 0.

train_frame_number_step:
  0: 8
  15000: 1

condition_config:
  control_aux: "" # dwpose_all
  clip_image: "background"
  concat_noise: ""
  ref_image: ""
  add_noise: ""
  foreground_mask: ""
  background_mask: ""

special_ref_index: 2
valid_seed: 42
recycle_seed: 200
warp_condition_use: true

# stage1 trained
appearance_controlnet_motion_checkpoint_path: "s3://radar/yangshurong/train12_magic_catnoise_CrossRefTemp_codeback_apt0_from2D10000step_warp04_DiffMotion_load_condition_ZT_OffNoi-2024-04-16T14-35-50/checkpoint-steps17000.ckpt"
# resume
resume_step_offset: 0
# set appearance time step, if not set , it will be None
appearance_time_step: 0

unet_additional_kwargs:
  unet_use_cross_frame_attention: false
  unet_use_temporal_attention: false
  use_motion_module: true # stage1
  motion_module_resolutions:
  - 1
  - 2
  - 4
  - 8
  motion_module_mid_block: false
  motion_module_decoder_only: false
  motion_module_type: Vanilla
  motion_module_kwargs:
    num_attention_heads: 8
    num_transformer_block: 1
    attention_block_types:
    - Temporal_Self
    - Temporal_Self
    temporal_position_encoding: true
    temporal_position_encoding_max_len: 32
    temporal_attention_dim_div: 1

  # Addition for image embeddings
  use_image_condition            : false
  use_condition_atten: ""


noise_scheduler_kwargs:
  num_train_timesteps: 1000
  beta_start:          0.00085
  beta_end:            0.012
  beta_schedule:       "scaled_linear" # 这部分animatediff和magic不一样？
  steps_offset:        1
  clip_sample:         false
  rescale_betas_zero_snr: true

data_module:          'animatediff.data.dataset_wds'
data_class:           'S3VideosIterableDataset'
train_data:
  data_dirs:          [
                      # 's3://public-datasets/Datasets/Videos/processed/CelebV_webdataset_20231211_videoblip',
                      # 's3://public-datasets/Datasets/Videos/processed/pexels_20231217',
                      # 's3://public-datasets/Datasets/Videos/processed/VFHQ_webdataset_20240404/'
                      's3://public-datasets/Datasets/Videos/processed/VFHQ_webdataset_20240410_dwpose_facebbox',
                      's3://public-datasets/Datasets/Videos/processed/CelebV_webdataset_2040410_dwpose_facebbox/',
                      's3://public-datasets/Datasets/Videos/processed/pexels_20240410_dwpose_facebbox/'

                      # 's3://ljj/Datasets/Videos/processed/hdvila100m_20231216',
                      # 's3://ljj/Datasets/Videos/processed/xiaohongshu_webdataset_20231212',
                      ]
  resolution:         [512, 512]
  frame_stride:       2
  video_length:       8
  shuffle:            true
  resampled:          true
  dataset_length:     1000000
  endpoint_url:       "http://oss.i.shaipower.com:80"

validation_data:
  source_image:
    - "./me_test_data/my_data_0.gif" # match
    - "./me_test_data/my_data_0.gif" # cross 8
    - "./new_test_data/000.jpg"
    - "./new_test_data/000.jpg"
    - "./new_test_data/000.jpg"
    - "./new_test_data/000.jpg"
    - "./new_test_data/000.jpg"


  video_path:
    - "./me_test_data/my_data_0.gif"
    - "./me_test_data/my_data_8.gif"
    - "./me_test_data/my_data_8.gif"
    - "./me_test_data/my_data_12.gif"
    - "./me_test_data/my_data_16.gif"
    - "./me_test_data/my_data_17.gif"
    - "./me_test_data/my_data_18.gif"

  num_inference_steps: 25
  guidance_scale: 4.5
  sample_size: [512, 512]
  # frame_stride: 1
  # S: 1

context:
  context_frames: 8
  context_stride: 1
  context_overlap: 4

# stage1 TODO: image_encoder部分？
trainable_modules:
  # - "appearance_encoder"
  # - "controlnet"
  # - "unet"
  - "motion_module"
  # - "unet.condition_input_layer.condition_atten_layer"

unet_checkpoint_path: ""

gradient_accumulation_steps: 4

learning_rate:    1.e-5
train_batch_size: 1
num_workers: 4

max_train_epoch:      100
max_train_steps:      1000000
checkpointing_epochs: -1
checkpointing_steps:  1000

validation_steps:       1000
validation_steps_tuple: []

mixed_precision_training: true
enable_xformers_memory_efficient_attention: true

is_debug: False
