source_image:
  # - "./me_test_data/my_data_0.gif" # match
  # - "./me_test_data/my_data_0.gif" # cross 8
  # - "./new_test_data/wulei_small.PNG"
  # - "./new_test_data/wulei_small.PNG"
  # - "./new_test_data/wulei_small.PNG"
  # - "./new_test_data/wulei_small.PNG"
  # - "./new_test_data/wulei_small.PNG"

  - "./new_test_data/Miley_Cyrus_Flowers.PNG"
  - "./new_test_data/juren.PNG"
  - "./new_test_data/heben.PNG"
  - "./new_test_data/Dua_Lipa.PNG"
  - "./new_test_data/David_Tao.PNG"
  - "./new_test_data/monalisa.PNG"

  - "./new_test_data/Miley_Cyrus_Flowers.PNG"
  - "./new_test_data/juren.PNG"
  - "./new_test_data/heben.PNG"
  - "./new_test_data/Dua_Lipa.PNG"
  - "./new_test_data/David_Tao.PNG"
  - "./new_test_data/monalisa.PNG"

  - "./new_test_data/vasa_case1.mp4"
  - "./new_test_data/vasa_case2.mp4"
  - "./new_test_data/vasa_case3.mp4"
  - "./new_test_data/vasa_case4.mp4"
  - "./new_test_data/vasa_case5.mp4"
  - "./new_test_data/vasa_case6.mp4"
  - "./new_test_data/vasa_case7.mp4"
  - "./new_test_data/vasa_case8.mp4"
  - "./new_test_data/vasa_case9.mp4"
  - "./new_test_data/vasa_case10.mp4"
  - "./new_test_data/vasa_case1.mp4"
  - "./new_test_data/vasa_case2.mp4"
  - "./new_test_data/vasa_case3.mp4"
  - "./new_test_data/vasa_case4.mp4"
  - "./new_test_data/vasa_case5.mp4"
  - "./new_test_data/vasa_case6.mp4"
  - "./new_test_data/vasa_case7.mp4"
  - "./new_test_data/vasa_case8.mp4"
  - "./new_test_data/vasa_case9.mp4"
  - "./new_test_data/vasa_case10.mp4"


video_path:
  # - "./me_test_data/my_data_0.gif"
  # - "./me_test_data/my_data_8.gif"
  # - "./me_test_data/my_data_8.gif"
  # - "./me_test_data/my_data_12.gif"
  # - "./me_test_data/my_data_16.gif"
  # - "./me_test_data/my_data_17.gif"
  # - "./me_test_data/my_data_18.gif"

  - "./new_test_data/Miley_Cyrus_Flowers.gif"
  - "./new_test_data/juren.gif"
  - "./new_test_data/heben.gif"
  - "./new_test_data/Dua_Lipa.gif"
  - "./new_test_data/David_Tao.gif"
  - "./new_test_data/monalisa.gif"

  - "./me_test_data/my_data_16.gif"
  - "./me_test_data/my_data_16.gif"
  - "./me_test_data/my_data_16.gif"
  - "./me_test_data/my_data_16.gif"
  - "./me_test_data/my_data_16.gif"
  - "./me_test_data/my_data_16.gif"

  - "./new_test_data/vasa_case1.mp4"
  - "./new_test_data/vasa_case2.mp4"
  - "./new_test_data/vasa_case3.mp4"
  - "./new_test_data/vasa_case4.mp4"
  - "./new_test_data/vasa_case5.mp4"
  - "./new_test_data/vasa_case6.mp4"
  - "./new_test_data/vasa_case7.mp4"
  - "./new_test_data/vasa_case8.mp4"
  - "./new_test_data/vasa_case9.mp4"
  - "./new_test_data/vasa_case10.mp4"
  - "./me_test_data/my_data_16.gif"
  - "./me_test_data/my_data_16.gif"
  - "./me_test_data/my_data_16.gif"
  - "./me_test_data/my_data_16.gif"
  - "./me_test_data/my_data_16.gif"
  - "./me_test_data/my_data_16.gif"
  - "./me_test_data/my_data_16.gif"
  - "./me_test_data/my_data_16.gif"
  - "./me_test_data/my_data_16.gif"
  - "./me_test_data/my_data_16.gif"
