use_image_encoder: false

# controlnet_type: '3d'
# controlnet_config: 'configs/inference/sparse_control.yaml'

# chose densepose, segface, dwpose, fromfile
# pretrained_model_path: "runwayml/stable-diffusion-v1-5"
pretrained_model_path: "/data/code/yangshurong/cache/StableDiffusion"
pretrained_vae_path: "/data/code/yangshurong/cache/magic_pretrain/sd-vae-ft-mse"
pretrained_controlnet_path: "/data/code/yangshurong/cache/magic_pretrain/MagicAnimate/densepose_controlnet"
pretrained_appearance_encoder_path: "/data/code/yangshurong/cache/magic_pretrain/MagicAnimate/appearance_encoder"
pretrained_unet_path: ""


motion_module: ""
# motion_module: "/root/.cache/yangshurong/magic_pretrain/MagicAnimate/temporal_attention/temporal_attention.ckpt"
# motion_module: "/root/.cache/yangshurong/animatediff_model/v3_sd15_mm.ckpt"

appearance_controlnet_motion_checkpoint_path: "s3://radar/yangshurong/train12_dwpose_stride2_codeback_apt0-2024-03-30T10-56-18/checkpoint-steps5000.ckpt"
# 如果指定motion_module，appearance_controlnet_motion_checkpoint_path中的motion会被覆盖

# set appearance time step, if not set , it will be None
appearance_time_step: 0
switch_control_to_source: false
crop_face_center: true

use_2d_cross_rate: 0.2
use_2d_rate: 1.0
control_aux_type: "dwpose_all"
remove_background: false
remove_referencenet: false
clip_image_type: "background"
concat_noise_image_type: ""
ref_image_type: "origin"
add_noise_image_type: ""
special_ref_index: 4
valid_seed: 42
save_every_image: true
do_classifier_free_guidance: true

savename: null

fusion_blocks: "midup"

seed:           [1]
steps:          25
guidance_scale: 4.5

context:
  context_frames: 16
  context_stride: 1
  context_overlap: 4

source_image:
  - "./me_test_data/my_data_0.gif" # match
  - "./me_test_data/my_data_0.gif" # cross 8
  - "./me_test_data/gaoyuanyuan.png" # special 12 
  - "./me_test_data/RealisticVision_firework.png" # special 8
  - "./me_test_data/my_data_16.gif" # match
  - "./me_test_data/my_data_16.gif" # cross 0
  - "./me_test_data/my_data_0.gif" # cross 17
  - "./me_test_data/my_data_17.gif" # cross 18

  - "./new_test_data/000.jpg"
  - "./new_test_data/000.jpg"
  - "./new_test_data/000.jpg"
  - "./new_test_data/000.jpg"
  - "./new_test_data/000.jpg"
  - "./new_test_data/000.jpg"
  - "./new_test_data/000.jpg"

video_path:
  - "./me_test_data/my_data_0.gif"
  - "./me_test_data/my_data_8.gif"
  - "./me_test_data/my_data_12.gif"
  - "./me_test_data/my_data_8.gif"
  - "./me_test_data/my_data_16.gif"
  - "./me_test_data/my_data_0.gif"
  - "./me_test_data/my_data_17.gif"
  - "./me_test_data/my_data_18.gif"

  - "./new_test_data/001.gif"
  - "./new_test_data/002.gif"
  - "./new_test_data/003.gif"
  - "./new_test_data/004.gif"
  - "./new_test_data/005.gif"
  - "./new_test_data/006.gif"
  - "./new_test_data/007.gif"


inference_config: "configs/inference/magic_inference.yaml"
size: [512, 512]
# 长度一致
L:    16
S:    1
I:    0
clip: 0
offset: 0
max_length: null
video_type: "condition"
invert_video: false
save_individual_videos: true

unet_additional_kwargs:
  unet_use_cross_frame_attention: false
  unet_use_temporal_attention: false
  use_motion_module: true
  motion_module_resolutions:
  - 1
  - 2
  - 4
  - 8
  motion_module_mid_block: false
  motion_module_decoder_only: false
  motion_module_type: Vanilla
  motion_module_kwargs:
    num_attention_heads: 8
    num_transformer_block: 1
    attention_block_types:
    - Temporal_Self
    - Temporal_Self
    temporal_position_encoding: true
    temporal_position_encoding_max_len: 24
    temporal_attention_dim_div: 1
  # Addition for image embeddings
  use_image_condition            : true

noise_scheduler_kwargs:
  beta_start: 0.00085
  beta_end: 0.012
  beta_schedule: "linear"
