use_image_encoder: false

# controlnet_type: '3d'
# controlnet_config: 'configs/inference/sparse_control.yaml'

# chose densepose, segface, dwpose, fromfile
# pretrained_model_path: "runwayml/stable-diffusion-v1-5"
pretrained_model_path: "/data/code/yangshurong/cache/StableDiffusion"
pretrained_vae_path: "/data/code/yangshurong/cache/magic_pretrain/sd-vae-ft-mse"
pretrained_controlnet_path: ""
pretrained_appearance_encoder_path: "/data/code/yangshurong/cache/magic_pretrain/MagicAnimate/appearance_encoder"
pretrained_unet_path: ""


motion_module: ""

appearance_controlnet_motion_checkpoint_path: "s3://radar/yangshurong/train12_magic_catnoise_CrossRefTemp_codeback_apt0_from2D10000step_warp04_DiffMotion_load_condition_ZT_OffNoi-2024-04-16T14-35-50/checkpoint-steps17000.ckpt"
# 如果指定motion_module，appearance_controlnet_motion_checkpoint_path中的motion会被覆盖

# set appearance time step, if not set , it will be None
appearance_time_step: 0
switch_control_to_source: true
crop_face_center: true

model_type: "unet_magic_noiseAttenST"

use_2d_cross_rate: 0.2
use_2d_rate: 1.0
condition_config:
  control_aux: "dwpose_all"
  clip_image: "background"
  concat_noise: ""
  ref_image: ""
  add_noise: ""
  foreground_mask: ""
  background_mask: ""
special_ref_index: 4
valid_seed: 42
save_every_image: true
do_classifier_free_guidance: true

savename: null

fusion_blocks: "midup"

seed:           [1]

context:
  context_frames: 8
  context_stride: 1
  context_overlap: 4

validation_data:
  num_inference_steps:          25
  guidance_scale: 4.
  source_image:
    # - "./me_test_data/my_data_0.gif" # match
    # - "./me_test_data/my_data_0.gif" # cross 8
    # - "./new_test_data/wulei_small.PNG"
    # - "./new_test_data/wulei_small.PNG"
    # - "./new_test_data/wulei_small.PNG"
    # - "./new_test_data/wulei_small.PNG"
    # - "./new_test_data/wulei_small.PNG"

    - "./new_test_data/Miley_Cyrus_Flowers.PNG"
    - "./new_test_data/juren.PNG"
    - "./new_test_data/heben.PNG"
    - "./new_test_data/Dua_Lipa.PNG"
    - "./new_test_data/David_Tao.PNG"
    - "./new_test_data/monalisa.PNG"

    - "./new_test_data/Miley_Cyrus_Flowers.PNG"
    - "./new_test_data/juren.PNG"
    - "./new_test_data/heben.PNG"
    - "./new_test_data/Dua_Lipa.PNG"
    - "./new_test_data/David_Tao.PNG"
    - "./new_test_data/monalisa.PNG"

    - "./new_test_data/vasa_case1.mp4"
    - "./new_test_data/vasa_case2.mp4"
    - "./new_test_data/vasa_case3.mp4"
    - "./new_test_data/vasa_case4.mp4"
    - "./new_test_data/vasa_case5.mp4"
    - "./new_test_data/vasa_case6.mp4"
    - "./new_test_data/vasa_case7.mp4"
    - "./new_test_data/vasa_case8.mp4"
    - "./new_test_data/vasa_case9.mp4"
    - "./new_test_data/vasa_case10.mp4"
    - "./new_test_data/vasa_case1.mp4"
    - "./new_test_data/vasa_case2.mp4"
    - "./new_test_data/vasa_case3.mp4"
    - "./new_test_data/vasa_case4.mp4"
    - "./new_test_data/vasa_case5.mp4"
    - "./new_test_data/vasa_case6.mp4"
    - "./new_test_data/vasa_case7.mp4"
    - "./new_test_data/vasa_case8.mp4"
    - "./new_test_data/vasa_case9.mp4"
    - "./new_test_data/vasa_case10.mp4"


  video_path:
    # - "./me_test_data/my_data_0.gif"
    # - "./me_test_data/my_data_8.gif"
    # - "./me_test_data/my_data_8.gif"
    # - "./me_test_data/my_data_12.gif"
    # - "./me_test_data/my_data_16.gif"
    # - "./me_test_data/my_data_17.gif"
    # - "./me_test_data/my_data_18.gif"

    - "./new_test_data/Miley_Cyrus_Flowers.mp4"
    - "./new_test_data/juren.mp4"
    - "./new_test_data/heben.mp4"
    - "./new_test_data/Dua_Lipa.mp4"
    - "./new_test_data/David_Tao.mp4"
    - "./new_test_data/monalisa.mp4"

    - "./me_test_data/my_data_16.gif"
    - "./me_test_data/my_data_16.gif"
    - "./me_test_data/my_data_16.gif"
    - "./me_test_data/my_data_16.gif"
    - "./me_test_data/my_data_16.gif"
    - "./me_test_data/my_data_16.gif"

    - "./new_test_data/vasa_case1.mp4"
    - "./new_test_data/vasa_case2.mp4"
    - "./new_test_data/vasa_case3.mp4"
    - "./new_test_data/vasa_case4.mp4"
    - "./new_test_data/vasa_case5.mp4"
    - "./new_test_data/vasa_case6.mp4"
    - "./new_test_data/vasa_case7.mp4"
    - "./new_test_data/vasa_case8.mp4"
    - "./new_test_data/vasa_case9.mp4"
    - "./new_test_data/vasa_case10.mp4"
    - "./me_test_data/my_data_16.gif"
    - "./me_test_data/my_data_16.gif"
    - "./me_test_data/my_data_16.gif"
    - "./me_test_data/my_data_16.gif"
    - "./me_test_data/my_data_16.gif"
    - "./me_test_data/my_data_16.gif"
    - "./me_test_data/my_data_16.gif"
    - "./me_test_data/my_data_16.gif"
    - "./me_test_data/my_data_16.gif"
    - "./me_test_data/my_data_16.gif"
  sample_size: [512, 512]

inference_config: "configs/inference/magic_inference.yaml"
# 长度一致
L:    16
S:    1
I:    0
clip: 0
offset: 0
max_length: null
video_type: "condition"
invert_video: false
save_individual_videos: true

unet_additional_kwargs:
  unet_use_cross_frame_attention: false
  unet_use_temporal_attention: false
  use_motion_module: true
  motion_module_resolutions:
  - 1
  - 2
  - 4
  - 8
  motion_module_mid_block: false
  motion_module_decoder_only: false
  motion_module_type: Vanilla
  motion_module_kwargs:
    num_attention_heads: 8
    num_transformer_block: 1
    attention_block_types:
    - Temporal_Self
    - Temporal_Self
    temporal_position_encoding: true
    temporal_position_encoding_max_len: 32
    temporal_attention_dim_div: 1
  # Addition for image embeddings
  use_image_condition            : true
  use_condition_atten: ""


noise_scheduler_kwargs:
  beta_start: 0.00085
  beta_end: 0.012
  beta_schedule: "linear"
