use_image_encoder: false

# controlnet_type: '3d'
# controlnet_config: 'configs/inference/sparse_control.yaml'

# chose densepose, segface, dwpose, fromfile
# pretrained_model_path: "runwayml/stable-diffusion-v1-5"
pretrained_model_path: "./weights/StableDiffusion"
pretrained_vae_path: "./weights/sd-vae-ft-mse"
pretrained_controlnet_path: ""
pretrained_appearance_encoder_path: "./weights/appearance_encoder"
pretrained_unet_path: ""


motion_module: ""

# appearance_controlnet_motion_checkpoint_path: "./weights/checkpoint-steps9000.ckpt"
appearance_controlnet_motion_checkpoint_path: "/data/checkpoint-steps9000.ckpt"
# appearance_controlnet_motion_checkpoint_path: "/home/wujuhao/code/train_logs/train1_catnoise_warp08_Ada-2024-06-13T13-10-44/checkpoints/checkpoint-steps4000.ckpt"
# 如果指定motion_module，appearance_controlnet_motion_checkpoint_path中的motion会被覆盖

# set appearance time step, if not set , it will be None
appearance_time_step: 0
switch_control_to_source: true
crop_face_center: true

model_type: "unet_magic_noiseAttenST_Ada"
# model_type: "unet_magic_noiseAttenST"

use_2d_cross_rate: 0.2
use_2d_rate: 1.0
control_aux_type: "dwpose_all"
remove_background: false
remove_referencenet: false
clip_image_type: "background"
concat_noise_image_type: "origin"
ref_image_type: "origin"
add_noise_image_type: ""
special_ref_index: 4
valid_seed: 42
save_every_image: true
do_classifier_free_guidance: true

savename: null

fusion_blocks: "midup"

seed:           [1]
steps:          25
guidance_scale: 4.5

context:
  context_frames: 4
  context_stride: 1
  context_overlap: 2

source_image:
  - "/home/wujuhao/code/back/lhd.jpg"

video_path:
  - "/home/wujuhao/code/back/driver.mp4"

inference_config: "configs/inference/magic_inference.yaml"
size: [512, 512]
# 长度一致
L:    16
S:    1
I:    0
clip: 0
offset: 0
max_length: null
video_type: "condition"
invert_video: false
save_individual_videos: true

unet_additional_kwargs:
  unet_use_cross_frame_attention: false
  unet_use_temporal_attention: false
  use_motion_module: true
  motion_module_resolutions:
  - 1
  - 2
  - 4
  - 8
  motion_module_mid_block: false
  motion_module_decoder_only: false
  motion_module_type: Vanilla
  motion_module_kwargs:
    num_attention_heads: 8
    num_transformer_block: 1
    attention_block_types:
    - Temporal_Self
    - Temporal_Self
    temporal_position_encoding: true
    temporal_position_encoding_max_len: 32
    temporal_attention_dim_div: 1
  # Addition for image embeddings
  use_image_condition            : true
  use_refer_ada: true


noise_scheduler_kwargs:
  beta_start: 0.00085
  beta_end: 0.012
  beta_schedule: "linear"
